#!/usr/bin/env sh
set -eu

export REDIS_BIND="${REDIS_BIND:-0.0.0.0}"
export REDIS_PORT="${REDIS_PORT:-6379}"
export REDIS_PROTECTED_MODE="${REDIS_PROTECTED_MODE:-yes}"
export REDIS_DATABASES="${REDIS_DATABASES:-16}"
export REDIS_TCP_BACKLOG="${REDIS_TCP_BACKLOG:-1024}"
export REDIS_TIMEOUT="${REDIS_TIMEOUT:-0}"
export REDIS_TCP_KEEPALIVE="${REDIS_TCP_KEEPALIVE:-60}"
export REDIS_MAXCLIENTS="${REDIS_MAXCLIENTS:-10000}"
export REDIS_LOGLEVEL="${REDIS_LOGLEVEL:-notice}"

export REDIS_MAXMEMORY="${REDIS_MAXMEMORY:-256mb}"
export REDIS_MAXMEMORY_POLICY="${REDIS_MAXMEMORY_POLICY:-allkeys-lfu}"
export REDIS_MAXMEMORY_SAMPLES="${REDIS_MAXMEMORY_SAMPLES:-10}"
export REDIS_LFU_LOG_FACTOR="${REDIS_LFU_LOG_FACTOR:-10}"
export REDIS_LFU_DECAY_TIME="${REDIS_LFU_DECAY_TIME:-1}"

export REDIS_IO_THREADS="${REDIS_IO_THREADS:-1}"
export REDIS_IO_THREADS_DO_READS="${REDIS_IO_THREADS_DO_READS:-yes}"

export REDIS_APPENDONLY="${REDIS_APPENDONLY:-no}"
export REDIS_APPENDFSYNC="${REDIS_APPENDFSYNC:-everysec}"

export REDIS_LAZYFREE_LAZY_EVICTION="${REDIS_LAZYFREE_LAZY_EVICTION:-yes}"
export REDIS_LAZYFREE_LAZY_EXPIRE="${REDIS_LAZYFREE_LAZY_EXPIRE:-yes}"
export REDIS_LAZYFREE_LAZY_SERVER_DEL="${REDIS_LAZYFREE_LAZY_SERVER_DEL:-yes}"
export REDIS_LAZYFREE_LAZY_USER_DEL="${REDIS_LAZYFREE_LAZY_USER_DEL:-yes}"
export REDIS_LAZYFREE_LAZY_USER_FLUSH="${REDIS_LAZYFREE_LAZY_USER_FLUSH:-yes}"

export REDIS_ACTIVE_DEFRAG="${REDIS_ACTIVE_DEFRAG:-yes}"
export REDIS_ACTIVE_DEFRAG_IGNORE_BYTES="${REDIS_ACTIVE_DEFRAG_IGNORE_BYTES:-100mb}"
export REDIS_ACTIVE_DEFRAG_THRESHOLD_LOWER="${REDIS_ACTIVE_DEFRAG_THRESHOLD_LOWER:-10}"
export REDIS_ACTIVE_DEFRAG_THRESHOLD_UPPER="${REDIS_ACTIVE_DEFRAG_THRESHOLD_UPPER:-100}"
export REDIS_ACTIVE_DEFRAG_CYCLE_MIN="${REDIS_ACTIVE_DEFRAG_CYCLE_MIN:-1}"
export REDIS_ACTIVE_DEFRAG_CYCLE_MAX="${REDIS_ACTIVE_DEFRAG_CYCLE_MAX:-25}"

export REDIS_HZ="${REDIS_HZ:-10}"
export REDIS_DYNAMIC_HZ="${REDIS_DYNAMIC_HZ:-yes}"
export REDIS_DISABLE_THP="${REDIS_DISABLE_THP:-yes}"
export REDIS_JEMALLOC_BG_THREAD="${REDIS_JEMALLOC_BG_THREAD:-yes}"

export REDIS_SLOWLOG_LOG_SLOWER_THAN="${REDIS_SLOWLOG_LOG_SLOWER_THAN:-10000}"
export REDIS_SLOWLOG_MAX_LEN="${REDIS_SLOWLOG_MAX_LEN:-256}"
export REDIS_LATENCY_MONITOR_THRESHOLD="${REDIS_LATENCY_MONITOR_THRESHOLD:-0}"

if [ -n "${REDIS_PASSWORD:-}" ]; then
  export REDIS_REQUIREPASS_DIRECTIVE="requirepass ${REDIS_PASSWORD}"
else
  export REDIS_REQUIREPASS_DIRECTIVE="# requirepass disabled"
fi

if [ -n "${REDIS_SAVE:-}" ]; then
  export REDIS_SAVE_DIRECTIVE="save ${REDIS_SAVE}"
else
  export REDIS_SAVE_DIRECTIVE='save ""'
fi

mkdir -p /usr/local/etc/redis /data

envsubst '
  ${REDIS_BIND}
  ${REDIS_PORT}
  ${REDIS_PROTECTED_MODE}
  ${REDIS_DATABASES}
  ${REDIS_TCP_BACKLOG}
  ${REDIS_TIMEOUT}
  ${REDIS_TCP_KEEPALIVE}
  ${REDIS_MAXCLIENTS}
  ${REDIS_LOGLEVEL}
  ${REDIS_REQUIREPASS_DIRECTIVE}
  ${REDIS_SAVE_DIRECTIVE}
  ${REDIS_APPENDONLY}
  ${REDIS_APPENDFSYNC}
  ${REDIS_MAXMEMORY}
  ${REDIS_MAXMEMORY_POLICY}
  ${REDIS_MAXMEMORY_SAMPLES}
  ${REDIS_LFU_LOG_FACTOR}
  ${REDIS_LFU_DECAY_TIME}
  ${REDIS_IO_THREADS}
  ${REDIS_IO_THREADS_DO_READS}
  ${REDIS_LAZYFREE_LAZY_EVICTION}
  ${REDIS_LAZYFREE_LAZY_EXPIRE}
  ${REDIS_LAZYFREE_LAZY_SERVER_DEL}
  ${REDIS_LAZYFREE_LAZY_USER_DEL}
  ${REDIS_LAZYFREE_LAZY_USER_FLUSH}
  ${REDIS_ACTIVE_DEFRAG}
  ${REDIS_ACTIVE_DEFRAG_IGNORE_BYTES}
  ${REDIS_ACTIVE_DEFRAG_THRESHOLD_LOWER}
  ${REDIS_ACTIVE_DEFRAG_THRESHOLD_UPPER}
  ${REDIS_ACTIVE_DEFRAG_CYCLE_MIN}
  ${REDIS_ACTIVE_DEFRAG_CYCLE_MAX}
  ${REDIS_HZ}
  ${REDIS_DYNAMIC_HZ}
  ${REDIS_DISABLE_THP}
  ${REDIS_JEMALLOC_BG_THREAD}
  ${REDIS_SLOWLOG_LOG_SLOWER_THAN}
  ${REDIS_SLOWLOG_MAX_LEN}
  ${REDIS_LATENCY_MONITOR_THRESHOLD}
' < /usr/local/share/vibe-wp/redis.conf.template > /usr/local/etc/redis/redis.conf

if [ "${1#-}" != "$1" ]; then
  set -- redis-server "$@"
fi

if [ "${1:-}" = "redis-server" ]; then
  set -- redis-server /usr/local/etc/redis/redis.conf
fi

exec /usr/local/bin/docker-entrypoint.sh "$@"
