services:
  nginx:
    environment:
      NGINX_ENABLE_HSTS: ${NGINX_ENABLE_HSTS:-1}
      NGINX_OPEN_FILE_CACHE_ERRORS: ${NGINX_OPEN_FILE_CACHE_ERRORS:-on}
      NGINX_FASTCGI_CACHE_INACTIVE: ${NGINX_FASTCGI_CACHE_INACTIVE:-60m}
      NGINX_FASTCGI_CACHE_MAX_SIZE: ${NGINX_FASTCGI_CACHE_MAX_SIZE:-2g}
    volumes:
      - type: volume
        source: wp_content
        target: /var/www/html/wp-content
        read_only: true
      - nginx_cache:/var/cache/nginx/wordpress

  wordpress:
    environment:
      WP_ENVIRONMENT_TYPE: ${WP_ENVIRONMENT_TYPE:-production}
      FORCE_SSL_ADMIN: ${FORCE_SSL_ADMIN:-1}
      DISALLOW_FILE_EDIT: ${DISALLOW_FILE_EDIT:-1}
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: ${PHP_OPCACHE_VALIDATE_TIMESTAMPS:-0}
      PHP_OPCACHE_REVALIDATE_FREQ: ${PHP_OPCACHE_REVALIDATE_FREQ:-0}
    volumes:
      - wp_content:/var/www/html/wp-content

  cron:
    environment:
      WP_ENVIRONMENT_TYPE: ${WP_ENVIRONMENT_TYPE:-production}
      FORCE_SSL_ADMIN: ${FORCE_SSL_ADMIN:-1}
      DISALLOW_FILE_EDIT: ${DISALLOW_FILE_EDIT:-1}
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: ${PHP_OPCACHE_VALIDATE_TIMESTAMPS:-0}
      PHP_OPCACHE_REVALIDATE_FREQ: ${PHP_OPCACHE_REVALIDATE_FREQ:-0}
    volumes:
      - wp_content:/var/www/html/wp-content

  db:
    environment:
      MARIADB_MAX_CONNECTIONS: ${MARIADB_MAX_CONNECTIONS:-200}
      MARIADB_THREAD_CACHE_SIZE: ${MARIADB_THREAD_CACHE_SIZE:-100}
      MARIADB_TABLE_OPEN_CACHE: ${MARIADB_TABLE_OPEN_CACHE:-8000}
      MARIADB_TABLE_DEFINITION_CACHE: ${MARIADB_TABLE_DEFINITION_CACHE:-4000}
      MARIADB_TMP_TABLE_SIZE: ${MARIADB_TMP_TABLE_SIZE:-128M}
      MARIADB_MAX_HEAP_TABLE_SIZE: ${MARIADB_MAX_HEAP_TABLE_SIZE:-128M}
      MARIADB_ARIA_PAGECACHE_BUFFER_SIZE: ${MARIADB_ARIA_PAGECACHE_BUFFER_SIZE:-256M}
      MARIADB_INNODB_BUFFER_POOL_SIZE: ${MARIADB_INNODB_BUFFER_POOL_SIZE:-512M}
      MARIADB_INNODB_LOG_FILE_SIZE: ${MARIADB_INNODB_LOG_FILE_SIZE:-512M}
      MARIADB_INNODB_IO_CAPACITY: ${MARIADB_INNODB_IO_CAPACITY:-1000}
      MARIADB_INNODB_IO_CAPACITY_MAX: ${MARIADB_INNODB_IO_CAPACITY_MAX:-4000}
      MARIADB_LONG_QUERY_TIME: ${MARIADB_LONG_QUERY_TIME:-1}

  redis:
    environment:
      REDIS_MAXMEMORY: ${REDIS_MAXMEMORY:-512mb}
      REDIS_MAXMEMORY_POLICY: ${REDIS_MAXMEMORY_POLICY:-allkeys-lfu}
      REDIS_IO_THREADS: ${REDIS_IO_THREADS:-2}
      REDIS_MAXCLIENTS: ${REDIS_MAXCLIENTS:-20000}
      REDIS_SLOWLOG_LOG_SLOWER_THAN: ${REDIS_SLOWLOG_LOG_SLOWER_THAN:-5000}

  wp:
    environment:
      WP_ENVIRONMENT_TYPE: ${WP_ENVIRONMENT_TYPE:-production}
      FORCE_SSL_ADMIN: ${FORCE_SSL_ADMIN:-1}
      DISALLOW_FILE_EDIT: ${DISALLOW_FILE_EDIT:-1}
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: ${PHP_OPCACHE_VALIDATE_TIMESTAMPS:-0}
      PHP_OPCACHE_REVALIDATE_FREQ: ${PHP_OPCACHE_REVALIDATE_FREQ:-0}
    volumes:
      - wp_content:/var/www/html/wp-content

volumes:
  wp_content:
