#!/bin/sh
set -eu

export NGINX_CLIENT_MAX_BODY_SIZE="${NGINX_CLIENT_MAX_BODY_SIZE:-128m}"
export NGINX_CLIENT_BODY_BUFFER_SIZE="${NGINX_CLIENT_BODY_BUFFER_SIZE:-256k}"
export NGINX_WORKER_CONNECTIONS="${NGINX_WORKER_CONNECTIONS:-4096}"
export NGINX_KEEPALIVE_TIMEOUT="${NGINX_KEEPALIVE_TIMEOUT:-65s}"
export NGINX_KEEPALIVE_REQUESTS="${NGINX_KEEPALIVE_REQUESTS:-1000}"
export NGINX_CLIENT_HEADER_TIMEOUT="${NGINX_CLIENT_HEADER_TIMEOUT:-15s}"
export NGINX_CLIENT_BODY_TIMEOUT="${NGINX_CLIENT_BODY_TIMEOUT:-60s}"
export NGINX_SEND_TIMEOUT="${NGINX_SEND_TIMEOUT:-30s}"
export NGINX_GZIP="${NGINX_GZIP:-on}"
export NGINX_GZIP_COMP_LEVEL="${NGINX_GZIP_COMP_LEVEL:-5}"
export NGINX_GZIP_MIN_LENGTH="${NGINX_GZIP_MIN_LENGTH:-1024}"
export NGINX_OPEN_FILE_CACHE="${NGINX_OPEN_FILE_CACHE:-on}"
export NGINX_OPEN_FILE_CACHE_MAX="${NGINX_OPEN_FILE_CACHE_MAX:-10000}"
export NGINX_OPEN_FILE_CACHE_INACTIVE="${NGINX_OPEN_FILE_CACHE_INACTIVE:-60s}"
export NGINX_OPEN_FILE_CACHE_VALID="${NGINX_OPEN_FILE_CACHE_VALID:-120s}"
export NGINX_OPEN_FILE_CACHE_MIN_USES="${NGINX_OPEN_FILE_CACHE_MIN_USES:-2}"
export NGINX_OPEN_FILE_CACHE_ERRORS="${NGINX_OPEN_FILE_CACHE_ERRORS:-off}"
export NGINX_STATIC_CACHE_CONTROL="${NGINX_STATIC_CACHE_CONTROL:-public,max-age=2592000}"
export NGINX_FASTCGI_CACHE_KEYS_ZONE_SIZE="${NGINX_FASTCGI_CACHE_KEYS_ZONE_SIZE:-128m}"
export NGINX_FASTCGI_CACHE_TTL="${NGINX_FASTCGI_CACHE_TTL:-10m}"
export NGINX_FASTCGI_REDIRECT_CACHE_TTL="${NGINX_FASTCGI_REDIRECT_CACHE_TTL:-1m}"
export NGINX_FASTCGI_CACHE_INACTIVE="${NGINX_FASTCGI_CACHE_INACTIVE:-30m}"
export NGINX_FASTCGI_CACHE_MAX_SIZE="${NGINX_FASTCGI_CACHE_MAX_SIZE:-1g}"
export NGINX_FASTCGI_CACHE_MIN_USES="${NGINX_FASTCGI_CACHE_MIN_USES:-1}"
export NGINX_FASTCGI_CACHE_LOCK_TIMEOUT="${NGINX_FASTCGI_CACHE_LOCK_TIMEOUT:-10s}"
export NGINX_FASTCGI_CONNECT_TIMEOUT="${NGINX_FASTCGI_CONNECT_TIMEOUT:-10s}"
export NGINX_FASTCGI_SEND_TIMEOUT="${NGINX_FASTCGI_SEND_TIMEOUT:-120s}"
export NGINX_FASTCGI_READ_TIMEOUT="${NGINX_FASTCGI_READ_TIMEOUT:-120s}"

case "$NGINX_GZIP" in
  1|true|yes)
    export NGINX_GZIP="on"
    ;;
  0|false|no)
    export NGINX_GZIP="off"
    ;;
esac

case "$NGINX_OPEN_FILE_CACHE_ERRORS" in
  1|true|yes)
    export NGINX_OPEN_FILE_CACHE_ERRORS="on"
    ;;
  0|false|no)
    export NGINX_OPEN_FILE_CACHE_ERRORS="off"
    ;;
esac

case "${NGINX_ACCESS_LOG:-1}" in
  0|off|false|no)
    export NGINX_ACCESS_LOG_DIRECTIVE="off"
    ;;
  *)
    export NGINX_ACCESS_LOG_DIRECTIVE="/var/log/nginx/access.log main"
    ;;
esac

case "$NGINX_OPEN_FILE_CACHE" in
  0|off|false|no)
    export NGINX_OPEN_FILE_CACHE_DIRECTIVE="open_file_cache off;"
    ;;
  *)
    export NGINX_OPEN_FILE_CACHE_DIRECTIVE="open_file_cache max=${NGINX_OPEN_FILE_CACHE_MAX} inactive=${NGINX_OPEN_FILE_CACHE_INACTIVE};"
    ;;
esac

if [ "${NGINX_ENABLE_HSTS:-0}" = "1" ]; then
  export NGINX_HSTS_HEADER='add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;'
else
  export NGINX_HSTS_HEADER=''
fi

mkdir -p /etc/nginx/conf.d /var/cache/nginx/wordpress

envsubst '
  ${NGINX_WORKER_CONNECTIONS}
  ${NGINX_KEEPALIVE_TIMEOUT}
  ${NGINX_KEEPALIVE_REQUESTS}
  ${NGINX_CLIENT_HEADER_TIMEOUT}
  ${NGINX_CLIENT_BODY_TIMEOUT}
  ${NGINX_SEND_TIMEOUT}
  ${NGINX_ACCESS_LOG_DIRECTIVE}
  ${NGINX_GZIP}
  ${NGINX_GZIP_COMP_LEVEL}
  ${NGINX_GZIP_MIN_LENGTH}
  ${NGINX_OPEN_FILE_CACHE_DIRECTIVE}
  ${NGINX_OPEN_FILE_CACHE_VALID}
  ${NGINX_OPEN_FILE_CACHE_MIN_USES}
  ${NGINX_OPEN_FILE_CACHE_ERRORS}
  ${NGINX_FASTCGI_CACHE_KEYS_ZONE_SIZE}
  ${NGINX_FASTCGI_CACHE_INACTIVE}
  ${NGINX_FASTCGI_CACHE_MAX_SIZE}
' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf

envsubst '
  ${NGINX_CLIENT_MAX_BODY_SIZE}
  ${NGINX_CLIENT_BODY_BUFFER_SIZE}
  ${NGINX_STATIC_CACHE_CONTROL}
  ${NGINX_FASTCGI_CACHE_TTL}
  ${NGINX_FASTCGI_REDIRECT_CACHE_TTL}
  ${NGINX_FASTCGI_CACHE_MIN_USES}
  ${NGINX_FASTCGI_CACHE_LOCK_TIMEOUT}
  ${NGINX_FASTCGI_CONNECT_TIMEOUT}
  ${NGINX_FASTCGI_SEND_TIMEOUT}
  ${NGINX_FASTCGI_READ_TIMEOUT}
  ${NGINX_HSTS_HEADER}
' < /etc/nginx/templates/site.conf.template > /etc/nginx/conf.d/default.conf

exec "$@"
