#!/usr/bin/env sh
set -eu

normalize_on_off() {
  case "$1" in
    1|true|TRUE|yes|YES|on|ON) printf 'ON' ;;
    0|false|FALSE|no|NO|off|OFF) printf 'OFF' ;;
    *) printf '%s' "$1" ;;
  esac
}

export MARIADB_CHARACTER_SET_SERVER="${MARIADB_CHARACTER_SET_SERVER:-utf8mb4}"
export MARIADB_COLLATION_SERVER="${MARIADB_COLLATION_SERVER:-utf8mb4_unicode_ci}"
export MARIADB_MAX_ALLOWED_PACKET="${MARIADB_MAX_ALLOWED_PACKET:-256M}"
export MARIADB_MAX_CONNECTIONS="${MARIADB_MAX_CONNECTIONS:-150}"
export MARIADB_THREAD_CACHE_SIZE="${MARIADB_THREAD_CACHE_SIZE:-100}"
export MARIADB_TABLE_OPEN_CACHE="${MARIADB_TABLE_OPEN_CACHE:-4000}"
export MARIADB_TABLE_DEFINITION_CACHE="${MARIADB_TABLE_DEFINITION_CACHE:-2000}"
export MARIADB_OPEN_FILES_LIMIT="${MARIADB_OPEN_FILES_LIMIT:-65535}"

export MARIADB_TMP_TABLE_SIZE="${MARIADB_TMP_TABLE_SIZE:-64M}"
export MARIADB_MAX_HEAP_TABLE_SIZE="${MARIADB_MAX_HEAP_TABLE_SIZE:-64M}"
export MARIADB_SORT_BUFFER_SIZE="${MARIADB_SORT_BUFFER_SIZE:-2M}"
export MARIADB_JOIN_BUFFER_SIZE="${MARIADB_JOIN_BUFFER_SIZE:-2M}"
export MARIADB_READ_BUFFER_SIZE="${MARIADB_READ_BUFFER_SIZE:-1M}"
export MARIADB_READ_RND_BUFFER_SIZE="${MARIADB_READ_RND_BUFFER_SIZE:-2M}"
export MARIADB_ARIA_PAGECACHE_BUFFER_SIZE="${MARIADB_ARIA_PAGECACHE_BUFFER_SIZE:-128M}"

export MARIADB_INNODB_BUFFER_POOL_SIZE="${MARIADB_INNODB_BUFFER_POOL_SIZE:-256M}"
export MARIADB_INNODB_LOG_FILE_SIZE="${MARIADB_INNODB_LOG_FILE_SIZE:-256M}"
export MARIADB_INNODB_LOG_BUFFER_SIZE="${MARIADB_INNODB_LOG_BUFFER_SIZE:-16M}"
export MARIADB_INNODB_FLUSH_LOG_AT_TRX_COMMIT="${MARIADB_INNODB_FLUSH_LOG_AT_TRX_COMMIT:-1}"
export MARIADB_INNODB_LINUX_AIO="${MARIADB_INNODB_LINUX_AIO:-aio}"
export MARIADB_INNODB_FLUSH_NEIGHBORS="${MARIADB_INNODB_FLUSH_NEIGHBORS:-0}"
export MARIADB_INNODB_IO_CAPACITY="${MARIADB_INNODB_IO_CAPACITY:-400}"
export MARIADB_INNODB_IO_CAPACITY_MAX="${MARIADB_INNODB_IO_CAPACITY_MAX:-2000}"
export MARIADB_INNODB_READ_IO_THREADS="${MARIADB_INNODB_READ_IO_THREADS:-4}"
export MARIADB_INNODB_WRITE_IO_THREADS="${MARIADB_INNODB_WRITE_IO_THREADS:-4}"
export MARIADB_INNODB_PURGE_THREADS="${MARIADB_INNODB_PURGE_THREADS:-4}"
export MARIADB_INNODB_STATS_PERSISTENT="$(normalize_on_off "${MARIADB_INNODB_STATS_PERSISTENT:-ON}")"
export MARIADB_INNODB_BUFFER_POOL_DUMP_AT_SHUTDOWN="$(normalize_on_off "${MARIADB_INNODB_BUFFER_POOL_DUMP_AT_SHUTDOWN:-ON}")"
export MARIADB_INNODB_BUFFER_POOL_LOAD_AT_STARTUP="$(normalize_on_off "${MARIADB_INNODB_BUFFER_POOL_LOAD_AT_STARTUP:-ON}")"
export MARIADB_INNODB_BUFFER_POOL_DUMP_PCT="${MARIADB_INNODB_BUFFER_POOL_DUMP_PCT:-25}"

# Security: LOAD DATA LOCAL INFILE. Default ON preserves stock MariaDB behavior
# for per-site servers; the shared multi-tenant server sets MARIADB_LOCAL_INFILE=0
# (SF-2) — WordPress never needs it, and disabling it removes a client-side
# file-read vector on a server shared by many tenants.
export MARIADB_LOCAL_INFILE="$(normalize_on_off "${MARIADB_LOCAL_INFILE:-ON}")"

export MARIADB_PERFORMANCE_SCHEMA="$(normalize_on_off "${MARIADB_PERFORMANCE_SCHEMA:-OFF}")"
export MARIADB_SLOW_QUERY_LOG="$(normalize_on_off "${MARIADB_SLOW_QUERY_LOG:-OFF}")"
export MARIADB_SLOW_QUERY_LOG_FILE="${MARIADB_SLOW_QUERY_LOG_FILE:-/var/lib/mysql/mariadb-slow.log}"
export MARIADB_LONG_QUERY_TIME="${MARIADB_LONG_QUERY_TIME:-2}"
export MARIADB_MIN_EXAMINED_ROW_LIMIT="${MARIADB_MIN_EXAMINED_ROW_LIMIT:-100}"
export MARIADB_LOG_QUERIES_NOT_USING_INDEXES="$(normalize_on_off "${MARIADB_LOG_QUERIES_NOT_USING_INDEXES:-OFF}")"

mkdir -p /etc/mysql/conf.d

envsubst '
  ${MARIADB_CHARACTER_SET_SERVER}
  ${MARIADB_COLLATION_SERVER}
  ${MARIADB_MAX_ALLOWED_PACKET}
  ${MARIADB_MAX_CONNECTIONS}
  ${MARIADB_THREAD_CACHE_SIZE}
  ${MARIADB_TABLE_OPEN_CACHE}
  ${MARIADB_TABLE_DEFINITION_CACHE}
  ${MARIADB_OPEN_FILES_LIMIT}
  ${MARIADB_TMP_TABLE_SIZE}
  ${MARIADB_MAX_HEAP_TABLE_SIZE}
  ${MARIADB_SORT_BUFFER_SIZE}
  ${MARIADB_JOIN_BUFFER_SIZE}
  ${MARIADB_READ_BUFFER_SIZE}
  ${MARIADB_READ_RND_BUFFER_SIZE}
  ${MARIADB_ARIA_PAGECACHE_BUFFER_SIZE}
  ${MARIADB_INNODB_BUFFER_POOL_SIZE}
  ${MARIADB_INNODB_LOG_FILE_SIZE}
  ${MARIADB_INNODB_LOG_BUFFER_SIZE}
  ${MARIADB_INNODB_FLUSH_LOG_AT_TRX_COMMIT}
  ${MARIADB_INNODB_LINUX_AIO}
  ${MARIADB_INNODB_FLUSH_NEIGHBORS}
  ${MARIADB_INNODB_IO_CAPACITY}
  ${MARIADB_INNODB_IO_CAPACITY_MAX}
  ${MARIADB_INNODB_READ_IO_THREADS}
  ${MARIADB_INNODB_WRITE_IO_THREADS}
  ${MARIADB_INNODB_PURGE_THREADS}
  ${MARIADB_INNODB_STATS_PERSISTENT}
  ${MARIADB_INNODB_BUFFER_POOL_DUMP_AT_SHUTDOWN}
  ${MARIADB_INNODB_BUFFER_POOL_LOAD_AT_STARTUP}
  ${MARIADB_INNODB_BUFFER_POOL_DUMP_PCT}
  ${MARIADB_LOCAL_INFILE}
  ${MARIADB_PERFORMANCE_SCHEMA}
  ${MARIADB_SLOW_QUERY_LOG}
  ${MARIADB_SLOW_QUERY_LOG_FILE}
  ${MARIADB_LONG_QUERY_TIME}
  ${MARIADB_MIN_EXAMINED_ROW_LIMIT}
  ${MARIADB_LOG_QUERIES_NOT_USING_INDEXES}
' < /etc/mysql/templates/vibe-wp.cnf.template > /etc/mysql/conf.d/z-vibe-wp.cnf

exec /usr/local/bin/docker-entrypoint.sh "$@"
